# Default values for chess.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repository:
  name: "arielrahamim/chess-app"
chessFrontend:
  tag: frontend-0.0.15-2d9745e6
  replicaCount: 1 
  service: 
  port: 3000
  nodePort: 30005
  host: localhost
  name: chessFrontend

chessBackend:
  tag: backend-0.0.11-4a78dcfb
  replicaCount: 1
  port: 5000
  nodePort: 30500
  host: localhost
  name: chessBackend

mongodb:
  tag: mongodb-0.0.2
  replicaCount: 1 
  service: "{{ .Release.Name }}-mongodb-svc"
  port: 27017
  username: "mongo_user"
  password: "mongo_pass"
  host: localhost

