# Default values for chess.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


chessFrontend:
  image: arielrahamim/chess-frontend
  tag: latest
  replicaCount: 1 
  service: 
  port: 3000
  portName: frontend-port
  nodePort: 30005
  configmap: chess-backend-configmap

chessBackend:
  image: arielrahamim/chess-backend
  tag: latest
  replicaCount: 1
  port: 5000
  portName: backend-port
  nodePort: 30500
  configmap: chess-frontend-configmap

mongodb:
  image: arielrahamim/chess-mongodb
  tag: latest
  replicaCount: 1 
  service: 
  port: 27017 
  portName: mongodb-port
  configmap: chess-mongodb-configmap
