apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deploy-role
rules:
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deploy-sa

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-token-jenkins-secret

  annotations:
    kubernetes.io/service-account.name: jenkins-deploy-sa 
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-jenkins-deploy

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deploy-role
subjects:
- kind: ServiceAccount
  name: jenkins-deploy-sa
