apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-mongo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d7bd1b09c5f24bd5 # replace with your EFS file system ID

