apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-jenkins
  name: deploy-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-jenkins
  template:
    metadata:
      labels:
        app: deploy-jenkins
    spec:
      serviceAccountName: jenkins
      volumes:
       - name: host-volume
         hostPath:
           path: /home/ec2-user/jenkins
      containers:
       - image: omerandori/chess-jenkins:latest
         name: jenkins
         volumeMounts:
          - name: host-volume
            mountPath: /var/jenkins_home
      tolerations:
       - key: "tool"
         operator: "Equal"
         value: "chess"
         effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In 
                values:
                - tool-chess