apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: deploy-jenkins
spec:
  selector:
    app: deploy-jenkins
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
       

