apiVersion: v1
kind: Service
metadata:      
  name: backend
  labels:
    app: chess
spec:
  selector:
    instance: pod-backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
       

