apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv-mongo
  namespace: kube-tool
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi

