apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "chess.name" . }}-frontend-deployment"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.chessFrontend.replicaCount }}
  selector:
    matchLabels: pod-frontend
  template:
    metadata:
      name: frontend
      labels:
        instance: pod-frontend
    spec:
      containers:
      - name: front
        image: "{{ .Values.chessFrontend.image }}:{{ .Values.chessFrontend.tag }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: configmap-frontend 

