apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend-deployment"
  labels: {{- include "chess.labels" . }} 
spec:
  replicas: {{ .Values.chessFrontend.replicaCount }}
  selector:
    matchLabels: 
      instance: pod-frontend
  template:
    metadata:
      labels:
        instance: pod-frontend
    spec:
      containers:
      - name: front
        image: "{{ .Values.repository.name }}:{{ .Values.chessFrontend.tag}}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-frontend-configmap

