apiVersion: v1
kind: Service
metadata:      
  name: "{{- include "chess.chart" . | indent 2 }}-frontend-svc"
  labels: {{- include "chess.labels" . | nindent 4 }}
spec:
  selector:
    instance: pod-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.chessFrontend.port }}
      name: {{ .Values.chessFrontend.portName }}
      targetPort: {{ .Values.chessFrontend.port }}
      nodePort: {{ .Values.chessFrontend.nodePort }}

