apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-backend-configmap"
data:
  CLIENT_URL: "{{ .Values.chessFrontend.host }}:{{ .Values.chessFrontend.port }}/api"
  SERVER_PORT: {{ .Values.chessBackend.port }}
