apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-backend-deployment"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.chessBackend.replicaCount }}
  selector:
    matchLabels:
      instance: pod-backend
  template:
    metadata:
      labels:
        instance: pod-backend
    spec:
      containers:
      - name: chess-backend
        image: "{{ .Values.repository.name }}:{{ .Values.chessBackend.tag}}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-backend-configmap
        - secretMapRef:
            name: {{ .Release.Name }}-backend-secret
