apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "chess.name" . }}-backend-deployment"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.chessBackend.replicaCount }}
  selector:
    matchLabels:
      instance: pod-backend
  template:
    metadata:
      name: backend
      labels:
        instance: pod-backend
    spec:
      containers:
      - name: chess-backend
        image: "{{ .Values.chessBackend.image }}:{{ .Values.chessBackend.tag }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: chess-backend-configmap
