apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-Backend"
  labels:
    app: chess
spec:
  replicas: {{ .Values.chess-backend.replicaCount }}
  selector:
    matchLabels:
      instance: pod-backend
  template:
    metadata:
      name: backend
      labels:
        instance: pod-backend
    spec:
      containers:
      - name: chess-backend
        image: {{ .Values.chess-backend.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: chess-backend-configmap
      # tolerations:
      #  - key: "tool"
      #    operator: "Equal"
      #    value: "chess"
      #    effect: "NoSchedule"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In 
      #           values:
      #           - tool-chess
