apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}--backend-secret
data:
  MONGO_URI: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.service }}:{{ .Values.mongodb.port }}"
  GMAIL_USER: ""
  GMAIL_PASS: ""