apiVersion: v1
kind: Service
metadata:      
  name: "{{ .Release.Name }}-backend-svc"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  selector:
    instance: pod-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.chessBackend.port }}
      name: "{{ .Values.chessBackend.name | lower }}-port"
      targetPort: {{ .Values.chessBackend.port }}
      nodePort: {{ .Values.chessBackend.nodePort }}

       

