apiVersion: v1
kind: Service
metadata:      
  name: "{{- include "chess.chart" . | indent 2 }}-backend-svc"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  selector:
    instance: pod-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.chessBackend.port }}
      name: {{ .Values.chessBackend.portName }}
      targetPort: {{ .Values.chessBackend.port }}
      nodePort: {{ .Values.chessBackend.nodePort }}

       

