apiVersion: v1
kind: Service
metadata:      
  name: backend
  labels:
    app: chess
spec:
  selector:
    instance: pod-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.chessBackend.port }}
      name: {{ .Values.chessBackend.portName }}
      targetPort: {{ .Values.chessBackend.port }}
      nodePort: {{ .Values.chessBackend.nodePort }}

       

