apiVersion: v1
kind: Service
metadata:      
  name: backend
  labels:
    app: chess
spec:
  selector:
    instance: pod-backend
  type: NodePort
  ports:
    - port: {{ .Values.chess-backend.service.port }}
      targetPort: {{ .Values.chess-backend.service.port }}
      nodePort: {{ .Values.chess-backend.service.nodePort }}
       

