apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: 
      certificate-authority-data: 
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: jenkins-deploy-sa
    name: jenkins-deploy-sa-kubernetes
current-context: jenkins-deploy-sa-kubernetes
users:
  - name: jenkins-deploy-sa
    user:
      token: 

