apiVersion: v1
kind: Service
metadata:
  name: "{{- include "chess.name" . }}-mongodb-svc"
  labels: {{- include "chess.labels" . | nindent 4 }} 
spec:
  selector:
    instance: pod-mongo
  ports:
  - port: 27017
    targetPort: 27017