apiVersion: apps/v1
kind: Statefulset
metadata:
  labels:
    app: chess
  name: "{{- include "chess.name" . }}-mongodb-deployment"
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      instance: pod-mongo
  template:
    metadata:
      labels:
        instance: pod-mongo
    spec:
      containers:
      - image: "{{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}"
        name: mongodb
        imagePullPolicy: Always
        args:
        - --port= {{ .Values.mongodb.port }}
        envFrom:
        - configMapRef:
            name: configmap-mongo
        volumeMounts:
        - mountPath: 
          name: mongo-volume
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: 
