apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: chess
  name: "{{ .Release.Name }}-mongodb-statefulset"
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      instance: pod-mongo
  template:
    metadata:
      labels:
        instance: pod-mongo
    spec:
      containers:
      - image: "{{ .Values.repository.name }}:{{ .Values.mongodb.tag}}"
        name: mongodb
        imagePullPolicy: Always
        envFrom:
        - secretKeyRef:
            name: {{ .Release.Name }}-mongodb-secret
      #   volumeMounts:
      #   - mountPath: 
      #     name: mongo-volume
      # volumes:
      # - name: mongo-volume
      #   persistentVolumeClaim:
      #     claimName: 
