name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_ci: 
        type: choice
        description: "the image to build"
        required: true
        options:
        - frontend
        - backend
        - mongodb

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
   
        - name: set env variable
          run: | 
            echo "latest_tag=$(git tag -l --sort=creatordate | grep ${{ github.event.inputs.image_ci }} | tail -1)" >> $GITHUB_ENV
            image=$(echo "$latest_tag" | cut -d "-" -f1)
            major=$(echo "$latest_tag" | cut -d "-" -f2 | cut -d "." -f1)
            minor=$(echo "$latest_tag" | cut -d "-" -f2 | cut -d "." -f2)
            patch=$(echo "$latest_tag" | cut -d "-" -f2 | cut -d "." -f3)
            
            patch=$((patch + 1))
            new_tag="$image.$major.$minor.$patch"
            latest_tag="$new_tag"
        - name: Debug latest_tag
          run: |
            echo "Latest Tag Var: $latest_tag"
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ${{ github.event.inputs.image_ci }}/.
            push: true
<<<<<<< HEAD
            tags: arielrahamim/chess-${{ github.event.inputs.image_ci }}:${{ github.env.latest_tag }}
=======
            tags: "arielrahamim/chess-${{ github.event.inputs.image_ci }}:$latest_tag"
>>>>>>> 8959161fa7b4188f81483d7893cd269f83f3e901

