name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_ci: 
        type: choice
        description: "the image to build"
        required: true
        options:
        - frontend
        - backend
        - mongodb

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - name: set env variable
          run: | 
              current_tag=$(git tag --sort=creatordate | grep ${{ github.event.inputs.image_ci }} | tail -n 1)
              image=$(echo $current_tag | cut -d "-" -f1)
              major=$(echo $current_tag | cut -d "-" -f2 | cut -d "." -f1)
              minor=$(echo $current_tag | cut -d "-" -f2 | cut -d "." -f2)
              patch=$(echo $current_tag | cut -d "-" -f2 | cut -d "." -f3)
              
              patch=$((patch + 1))
              new_tag=""
              new_tag="$image-$major.$minor.$patch"
              echo "latest_tag=${new_tag}" >> $GITHUB_ENV

              echo "aviv"
              echo "This Is The Image:$image"
              echo "This Is The Major:$major"
              echo "This Is The Minor:$minor"
              echo "This Is The Patch:$Patch"
              echo $new_tag

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ${{ github.event.inputs.image_ci }}/.
            push: true
            tags: arielrahamim/chess-${{ github.event.inputs.image_ci }}:${{ env.latest_tag }}

